import {
  Project,
  WorkLog,
  Material,
  Worker,
  Supplier,
  User,
  MaterialRequest,
} from "./types";

// Данные пользователей
export const mockUsers: User[] = [
  {
    id: "1",
    name: "Ахмад Рахими",
    role: "employer",
    email: "ahmad@stroitelstvo.tj",
    avatar: "👨‍💼",
  },
  {
    id: "2",
    name: "Фарид Назаров",
    role: "worker",
    email: "farid@rabochiy.tj",
    avatar: "👷‍♂️",
  },
  {
    id: "3",
    name: "Гульнора Снабжение ООО",
    role: "supplier",
    email: "info@gulnora.tj",
    avatar: "🏢",
  },
];

// Данны�� проектов
export const mockProjects: Project[] = [
  {
    id: "proj-1",
    name: "Жилой комплекс А",
    description: "Строительство 3-этажного жилого дома в Душанбе",
    startDate: "2024-01-15",
    endDate: "2024-06-30",
    status: "active",
    progress: 65,
    totalArea: 1200,
    completedArea: 780,
    location: "Душанбе, Таджикистан",
    budget: 250000,
    spentAmount: 162500,
    assignedWorkers: ["2", "worker-2", "worker-3"],
    materials: [],
    workLogs: [],
  },
  {
    id: "proj-2",
    name: "Офисное здание Б",
    description: "Современный офисный комплекс со стеклянным фасадом",
    startDate: "2024-02-01",
    endDate: "2024-08-15",
    status: "active",
    progress: 30,
    totalArea: 800,
    completedArea: 240,
    location: "Худжанд, Таджикистан",
    budget: 180000,
    spentAmount: 54000,
    assignedWorkers: ["worker-2", "worker-4"],
    materials: [],
    workLogs: [],
  },
  {
    id: "proj-3",
    name: "Реконструкция школы",
    description: "Полная реконструкция здания местной школы",
    startDate: "2023-10-01",
    endDate: "2024-01-31",
    status: "completed",
    progress: 100,
    totalArea: 600,
    completedArea: 600,
    location: "Хорог, Таджикистан",
    budget: 120000,
    spentAmount: 118000,
    assignedWorkers: ["2", "worker-3"],
    materials: [],
    workLogs: [],
  },
  {
    id: "proj-4",
    name: "Таджикский культурный центр",
    description: "Здание традиционной архитектуры с современными удобствами",
    startDate: "2024-03-01",
    endDate: "2024-09-30",
    status: "active",
    progress: 45,
    totalArea: 950,
    completedArea: 427,
    location: "Душанбе, Таджикистан",
    budget: 320000,
    spentAmount: 144000,
    assignedWorkers: ["2", "worker-2"],
    materials: [],
    workLogs: [],
  },
  {
    id: "proj-5",
    name: "Горный туристический комплекс",
    description: "Эко-курорт класса люкс в Памирских горах",
    startDate: "2024-02-15",
    endDate: "2024-07-20",
    status: "active",
    progress: 25,
    totalArea: 600,
    completedArea: 150,
    location: "Хорог, Горно-Бадахшан",
    budget: 280000,
    spentAmount: 70000,
    assignedWorkers: ["2", "worker-3", "worker-4"],
    materials: [],
    workLogs: [],
  },
  {
    id: "proj-6",
    name: "Общественная поликлиника",
    description: "Современное медицинское учреждение для местного населения",
    startDate: "2024-01-10",
    endDate: "2024-05-15",
    status: "active",
    progress: 80,
    totalArea: 400,
    completedArea: 320,
    location: "Исфара, Согдийская область",
    budget: 150000,
    spentAmount: 120000,
    assignedWorkers: ["2"],
    materials: [],
    workLogs: [],
  },
  {
    id: "proj-7",
    name: "Музей наследия Шелкового пути",
    description:
      "Исторический музей, демонстрирующий наследие Шелкового пути Таджикистана",
    startDate: "2023-11-01",
    endDate: "2024-04-30",
    status: "active",
    progress: 90,
    totalArea: 1100,
    completedArea: 990,
    location: "Худжанд, Согдийская область",
    budget: 450000,
    spentAmount: 405000,
    assignedWorkers: ["2", "worker-2", "worker-3"],
    materials: [],
    workLogs: [],
  },
  {
    id: "proj-8",
    name: "Инфраструктура солнечной электростанции",
    description: "Проект возобновляемой энергии с установкой солнечных панелей",
    startDate: "2024-01-20",
    endDate: "2024-06-10",
    status: "planning",
    progress: 5,
    totalArea: 2000,
    completedArea: 100,
    location: "Бохтар, Хатлонская область",
    budget: 800000,
    spentAmount: 40000,
    assignedWorkers: ["2", "worker-4"],
    materials: [],
    workLogs: [],
  },
  {
    id: "proj-9",
    name: "Водоочистная станция",
    description: "Современное сооружение очистки воды для сельских районов",
    startDate: "2023-12-01",
    endDate: "2024-08-31",
    status: "paused",
    progress: 35,
    totalArea: 750,
    completedArea: 262,
    location: "Вахдат, Районы республиканского подчинения",
    budget: 380000,
    spentAmount: 133000,
    assignedWorkers: ["2", "worker-3"],
    materials: [],
    workLogs: [],
  },
];

// Данные рабочих
export const mockWorkers: Worker[] = [
  {
    id: "worker-1",
    name: "Фарид Назаров",
    specialization: "Каменщик",
    ratePerSquareMeter: 15,
    totalEarnings: 26040,
    projectsAssigned: [
      "proj-1",
      "proj-3",
      "proj-4",
      "proj-5",
      "proj-6",
      "proj-7",
      "proj-8",
      "proj-9",
    ],
    phone: "+992 92 123 4567",
  },
  {
    id: "worker-2",
    name: "Джамшид Каримов",
    specialization: "Столяр",
    ratePerSquareMeter: 18,
    totalEarnings: 18900,
    projectsAssigned: ["proj-1", "proj-2"],
    phone: "+992 93 234 5678",
  },
  {
    id: "worker-3",
    name: "Санджар Мирзаев",
    specialization: "Электрик",
    ratePerSquareMeter: 20,
    totalEarnings: 16800,
    projectsAssigned: ["proj-1", "proj-3"],
    phone: "+992 91 345 6789",
  },
  {
    id: "worker-4",
    name: "Рустам Асадов",
    specialization: "Маляр",
    ratePerSquareMeter: 12,
    totalEarnings: 8640,
    projectsAssigned: ["proj-2"],
    phone: "+992 95 456 7890",
  },
];

// Данные материалов
export const mockMaterials: Material[] = [
  {
    id: "mat-1",
    name: "Цемент",
    unit: "кг",
    totalQuantity: 5000,
    usedQuantity: 3200,
    remainingQuantity: 1800,
    pricePerUnit: 0.8,
    supplier: "ООО Гульнора Снабжение",
    deliveryDate: "2024-01-10",
  },
  {
    id: "mat-2",
    name: "Стальная арматура",
    unit: "кг",
    totalQuantity: 2000,
    usedQuantity: 1300,
    remainingQuantity: 700,
    pricePerUnit: 2.5,
    supplier: "Металлстрой ООО",
    deliveryDate: "2024-01-12",
  },
  {
    id: "mat-3",
    name: "Стекловолокно",
    unit: "м²",
    totalQuantity: 800,
    usedQuantity: 520,
    remainingQuantity: 280,
    pricePerUnit: 12,
    supplier: "ООО Гульнора Снабжение",
    deliveryDate: "2024-01-15",
  },
  {
    id: "mat-4",
    name: "Краска",
    unit: "л",
    totalQuantity: 300,
    usedQuantity: 45,
    remainingQuantity: 255,
    pricePerUnit: 8,
    supplier: "КолорМакс Трейдинг",
    deliveryDate: "2024-02-01",
  },
  {
    id: "mat-5",
    name: "Традиционные каменные блоки",
    unit: "шт",
    totalQuantity: 500,
    usedQuantity: 120,
    remainingQuantity: 380,
    pricePerUnit: 25,
    supplier: "Таджикский карьер ООО",
    deliveryDate: "2024-03-01",
  },
];

// Журнал работ
export const mockWorkLogs: WorkLog[] = [
  {
    id: "log-1",
    workerId: "2",
    workerName: "Фарид Назаров",
    projectId: "proj-1",
    date: "2024-01-20",
    areaCompleted: 25,
    description: "Завершена кладочная работа на восточной стене первого этажа",
    ratePerSquareMeter: 15,
    earnings: 375,
  },
  {
    id: "log-2",
    workerId: "worker-2",
    workerName: "Джамшид Каримов",
    projectId: "proj-1",
    date: "2024-01-20",
    areaCompleted: 18,
    description: "Установлен деревянный каркас для окон",
    ratePerSquareMeter: 18,
    earnings: 324,
  },
  {
    id: "log-3",
    workerId: "2",
    workerName: "Фарид Назаров",
    projectId: "proj-1",
    date: "2024-01-21",
    areaCompleted: 30,
    description: "Продолжена кладочная работа на первом этаже",
    ratePerSquareMeter: 15,
    earnings: 450,
  },
  {
    id: "log-4",
    workerId: "2",
    workerName: "Фарид Назаров",
    projectId: "proj-4",
    date: "2024-03-05",
    areaCompleted: 22,
    description: "Традиционная каменная кладка фасада культурного центра",
    ratePerSquareMeter: 15,
    earnings: 330,
  },
  {
    id: "log-5",
    workerId: "2",
    workerName: "Фарид Назаров",
    projectId: "proj-5",
    date: "2024-02-20",
    areaCompleted: 15,
    description: "Фундаментальные работы для горного комплекса",
    ratePerSquareMeter: 15,
    earnings: 225,
  },
  {
    id: "log-6",
    workerId: "2",
    workerName: "Фарид Назаров",
    projectId: "proj-6",
    date: "2024-01-25",
    areaCompleted: 28,
    description: "Возведение внутренних стен поликлиники",
    ratePerSquareMeter: 15,
    earnings: 420,
  },
  {
    id: "log-7",
    workerId: "2",
    workerName: "Фарид Назаров",
    projectId: "proj-7",
    date: "2024-01-30",
    areaCompleted: 35,
    description: "Финальные кладочные работы в выставочных залах музея",
    ratePerSquareMeter: 15,
    earnings: 525,
  },
  {
    id: "log-8",
    workerId: "2",
    workerName: "Фарид Назаров",
    projectId: "proj-1",
    date: "2024-01-22",
    areaCompleted: 26,
    description: "Завершение наружных стен жилого комплекса",
    ratePerSquareMeter: 15,
    earnings: 390,
  },
  {
    id: "log-9",
    workerId: "2",
    workerName: "Фарид Назаров",
    projectId: "proj-9",
    date: "2023-12-15",
    areaCompleted: 20,
    description: "Бетонные фундаментальные работы водоочистного сооружения",
    ratePerSquareMeter: 15,
    earnings: 300,
  },
];

// Navigation items are now handled in BottomNavigation component with proper icons

// Единицы измерения материалов
export const materialUnits = ["кг", "м²", "л", "шт", "м³", "м"];

// Статусы проектов
export const projectStatuses = [
  { value: "planning", label: "Планирование", color: "bg-yellow-500" },
  { value: "active", label: "Активный", color: "bg-green-500" },
  { value: "paused", label: "Приостановлен", color: "bg-orange-500" },
  { value: "completed", label: "Завершен", color: "bg-blue-500" },
];

// Заявки на материалы
export const mockMaterialRequests: MaterialRequest[] = [
  {
    id: "req-1",
    workerId: "2",
    workerName: "Фарид Назаров",
    projectId: "proj-1",
    projectName: "Жилой комплекс А",
    materialName: "Цемент",
    requestedQuantity: 500,
    unit: "кг",
    urgency: "high",
    reason: "Нехватка цемента, необходим для фундаментальных работ",
    status: "pending",
    requestDate: "2024-01-22",
    notes: "Необходимо к пятнице для соблюдения графика",
  },
  {
    id: "req-2",
    workerId: "worker-2",
    workerName: "Джамшид Каримов",
    projectId: "proj-2",
    projectName: "Офисное здание Б",
    materialName: "Стальная арматура",
    requestedQuantity: 200,
    unit: "kg",
    urgency: "medium",
    reason: "Для армирования колонны требуется дополнительная арматура",
    status: "approved",
    requestDate: "2024-01-20",
    approvedBy: "Ахмад Рахими",
    approvedDate: "2024-01-21",
  },
  {
    id: "req-3",
    workerId: "worker-4",
    workerName: "Рустам Асадов",
    projectId: "proj-2",
    projectName: "Офисное здание Б",
    materialName: "Краска",
    requestedQuantity: 50,
    unit: "L",
    urgency: "low",
    reason: "Нужно больше краски для внутренних стен",
    status: "fulfilled",
    requestDate: "2024-01-18",
    approvedBy: "Ахмад Рахими",
    approvedDate: "2024-01-19",
  },
  {
    id: "req-4",
    workerId: "2",
    workerName: "Фарид Назаров",
    projectId: "proj-4",
    projectName: "Таджикский Культурный центр",
    materialName: "Традиционные каменные блоки",
    requestedQuantity: 300,
    unit: "pcs",
    urgency: "medium",
    reason:
      "Нужны традиционные каменные блоки для аутентичного фасада культурного центра",
    status: "pending",
    requestDate: "2024-03-10",
    notes: "Отдавайте предпочтение местному каменному карьеру для сохранения культурной аутентичности",
  },
];

// Специализации рабочих
export const workerSpecializations = [
  "Каменщик",
  "Столяр",
  "Электрик",
  "Сантехник",
  "Маляр",
  "Кровельщик",
  "Сварщик",
  "Подсобный рабочий",
];

// Уровни срочности заявок на материалы
export const urgencyLevels = [
  { value: "low", label: "Низкий приоритет", color: "bg-green-500" },
  { value: "medium", label: "Средний приоритет", color: "bg-yellow-500" },
  { value: "high", label: "Высокий приоритет", color: "bg-red-500" },
];

// Статусы заявок на материалы
export const requestStatuses = [
  { value: "pending", label: "В ожидании", color: "bg-yellow-500" },
  { value: "approved", label: "Одо��рено", color: "bg-blue-500" },
  { value: "rejected", label: "Отклонено", color: "bg-red-500" },
  { value: "fulfilled", label: "Выполнено", color: "bg-green-500" },
];
