import {
  Project,
  WorkLog,
  Material,
  Worker,
  Supplier,
  User,
  MaterialRequest,
} from "./types";

// Mock user data
export const mockUsers: User[] = [
  {
    id: "1",
    name: "Ahmad Rahimi",
    role: "employer",
    email: "ahmad@construction.tj",
    avatar: "👨‍💼",
  },
  {
    id: "2",
    name: "Farid Nazarov",
    role: "worker",
    email: "farid@worker.tj",
    avatar: "👷‍♂️",
  },
  {
    id: "3",
    name: "Gulnora Supply Co.",
    role: "supplier",
    email: "info@gulnora.tj",
    avatar: "🏢",
  },
];

// Mock projects data
export const mockProjects: Project[] = [
  {
    id: "proj-1",
    name: "Residential Complex A",
    description: "Construction of 3-story residential building in Dushanbe",
    startDate: "2024-01-15",
    endDate: "2024-06-30",
    status: "active",
    progress: 65,
    totalArea: 1200,
    completedArea: 780,
    location: "Dushanbe, Tajikistan",
    budget: 250000,
    spentAmount: 162500,
    assignedWorkers: ["worker-1", "worker-2", "worker-3"],
    materials: [],
    workLogs: [],
  },
  {
    id: "proj-2",
    name: "Office Building B",
    description: "Modern office complex with glass facade",
    startDate: "2024-02-01",
    endDate: "2024-08-15",
    status: "active",
    progress: 30,
    totalArea: 800,
    completedArea: 240,
    location: "Khujand, Tajikistan",
    budget: 180000,
    spentAmount: 54000,
    assignedWorkers: ["worker-2", "worker-4"],
    materials: [],
    workLogs: [],
  },
  {
    id: "proj-3",
    name: "School Renovation",
    description: "Complete renovation of local school building",
    startDate: "2023-10-01",
    endDate: "2024-01-31",
    status: "completed",
    progress: 100,
    totalArea: 600,
    completedArea: 600,
    location: "Khorog, Tajikistan",
    budget: 120000,
    spentAmount: 118000,
    assignedWorkers: ["worker-1", "worker-3"],
    materials: [],
    workLogs: [],
  },
  {
    id: "proj-4",
    name: "Tajik Cultural Center",
    description: "Traditional architectural building with modern amenities",
    startDate: "2024-03-01",
    endDate: "2024-09-30",
    status: "active",
    progress: 45,
    totalArea: 950,
    completedArea: 427,
    location: "Dushanbe, Tajikistan",
    budget: 320000,
    spentAmount: 144000,
    assignedWorkers: ["worker-1", "worker-2"],
    materials: [],
    workLogs: [],
  },
  {
    id: "proj-5",
    name: "Mountain Resort Lodge",
    description: "Luxury eco-friendly lodge in the Pamir Mountains",
    startDate: "2024-02-15",
    endDate: "2024-07-20",
    status: "active",
    progress: 25,
    totalArea: 600,
    completedArea: 150,
    location: "Khorog, Gorno-Badakhshan",
    budget: 280000,
    spentAmount: 70000,
    assignedWorkers: ["worker-1", "worker-3", "worker-4"],
    materials: [],
    workLogs: [],
  },
  {
    id: "proj-6",
    name: "Community Health Clinic",
    description: "Modern healthcare facility for local community",
    startDate: "2024-01-10",
    endDate: "2024-05-15",
    status: "active",
    progress: 80,
    totalArea: 400,
    completedArea: 320,
    location: "Isfara, Sughd Province",
    budget: 150000,
    spentAmount: 120000,
    assignedWorkers: ["worker-1"],
    materials: [],
    workLogs: [],
  },
  {
    id: "proj-7",
    name: "Silk Road Heritage Museum",
    description: "Historical museum showcasing Tajikistan's Silk Road heritage",
    startDate: "2023-11-01",
    endDate: "2024-04-30",
    status: "active",
    progress: 90,
    totalArea: 1100,
    completedArea: 990,
    location: "Khujand, Sughd Province",
    budget: 450000,
    spentAmount: 405000,
    assignedWorkers: ["worker-1", "worker-2", "worker-3"],
    materials: [],
    workLogs: [],
  },
  {
    id: "proj-8",
    name: "Solar Farm Infrastructure",
    description: "Renewable energy project with solar panel installations",
    startDate: "2024-01-20",
    endDate: "2024-06-10",
    status: "planning",
    progress: 5,
    totalArea: 2000,
    completedArea: 100,
    location: "Bokhtar, Khatlon Province",
    budget: 800000,
    spentAmount: 40000,
    assignedWorkers: ["worker-1", "worker-4"],
    materials: [],
    workLogs: [],
  },
  {
    id: "proj-9",
    name: "Water Treatment Plant",
    description: "Modern water purification facility for rural communities",
    startDate: "2023-12-01",
    endDate: "2024-08-31",
    status: "paused",
    progress: 35,
    totalArea: 750,
    completedArea: 262,
    location: "Vahdat, Districts of Republican Subordination",
    budget: 380000,
    spentAmount: 133000,
    assignedWorkers: ["worker-1", "worker-3"],
    materials: [],
    workLogs: [],
  },
];

// Mock workers data
export const mockWorkers: Worker[] = [
  {
    id: "worker-1",
    name: "Farid Nazarov",
    specialization: "Mason",
    ratePerSquareMeter: 15,
    totalEarnings: 23400,
    projectsAssigned: ["proj-1", "proj-3"],
    phone: "+992 92 123 4567",
  },
  {
    id: "worker-2",
    name: "Jamshid Karimov",
    specialization: "Carpenter",
    ratePerSquareMeter: 18,
    totalEarnings: 18900,
    projectsAssigned: ["proj-1", "proj-2"],
    phone: "+992 93 234 5678",
  },
  {
    id: "worker-3",
    name: "Sanjar Mirzaev",
    specialization: "Electrician",
    ratePerSquareMeter: 20,
    totalEarnings: 16800,
    projectsAssigned: ["proj-1", "proj-3"],
    phone: "+992 91 345 6789",
  },
  {
    id: "worker-4",
    name: "Rustam Asadov",
    specialization: "Painter",
    ratePerSquareMeter: 12,
    totalEarnings: 8640,
    projectsAssigned: ["proj-2"],
    phone: "+992 95 456 7890",
  },
];

// Mock materials data
export const mockMaterials: Material[] = [
  {
    id: "mat-1",
    name: "Cement",
    unit: "kg",
    totalQuantity: 5000,
    usedQuantity: 3200,
    remainingQuantity: 1800,
    pricePerUnit: 0.8,
    supplier: "Gulnora Supply Co.",
    deliveryDate: "2024-01-10",
  },
  {
    id: "mat-2",
    name: "Steel Rebar",
    unit: "kg",
    totalQuantity: 2000,
    usedQuantity: 1300,
    remainingQuantity: 700,
    pricePerUnit: 2.5,
    supplier: "Metallstroy LLC",
    deliveryDate: "2024-01-12",
  },
  {
    id: "mat-3",
    name: "Fiberglass",
    unit: "m²",
    totalQuantity: 800,
    usedQuantity: 520,
    remainingQuantity: 280,
    pricePerUnit: 12,
    supplier: "Gulnora Supply Co.",
    deliveryDate: "2024-01-15",
  },
  {
    id: "mat-4",
    name: "Paint",
    unit: "L",
    totalQuantity: 300,
    usedQuantity: 45,
    remainingQuantity: 255,
    pricePerUnit: 8,
    supplier: "ColorMax Trading",
    deliveryDate: "2024-02-01",
  },
];

// Mock work logs
export const mockWorkLogs: WorkLog[] = [
  {
    id: "log-1",
    workerId: "worker-1",
    workerName: "Farid Nazarov",
    projectId: "proj-1",
    date: "2024-01-20",
    areaCompleted: 25,
    description: "Completed masonry work on ground floor east wall",
    ratePerSquareMeter: 15,
    earnings: 375,
  },
  {
    id: "log-2",
    workerId: "worker-2",
    workerName: "Jamshid Karimov",
    projectId: "proj-1",
    date: "2024-01-20",
    areaCompleted: 18,
    description: "Installed wooden framework for windows",
    ratePerSquareMeter: 18,
    earnings: 324,
  },
  {
    id: "log-3",
    workerId: "worker-1",
    workerName: "Farid Nazarov",
    projectId: "proj-1",
    date: "2024-01-21",
    areaCompleted: 30,
    description: "Continued masonry work on ground floor",
    ratePerSquareMeter: 15,
    earnings: 450,
  },
  {
    id: "log-4",
    workerId: "worker-1",
    workerName: "Farid Nazarov",
    projectId: "proj-4",
    date: "2024-03-05",
    areaCompleted: 22,
    description: "Traditional stonework for cultural center facade",
    ratePerSquareMeter: 15,
    earnings: 330,
  },
  {
    id: "log-5",
    workerId: "worker-1",
    workerName: "Farid Nazarov",
    projectId: "proj-5",
    date: "2024-02-20",
    areaCompleted: 15,
    description: "Foundation work for mountain lodge",
    ratePerSquareMeter: 15,
    earnings: 225,
  },
  {
    id: "log-6",
    workerId: "worker-1",
    workerName: "Farid Nazarov",
    projectId: "proj-6",
    date: "2024-01-25",
    areaCompleted: 28,
    description: "Interior wall construction for health clinic",
    ratePerSquareMeter: 15,
    earnings: 420,
  },
  {
    id: "log-7",
    workerId: "worker-1",
    workerName: "Farid Nazarov",
    projectId: "proj-7",
    date: "2024-01-30",
    areaCompleted: 35,
    description: "Final masonry touches on museum exhibition halls",
    ratePerSquareMeter: 15,
    earnings: 525,
  },
  {
    id: "log-8",
    workerId: "worker-1",
    workerName: "Farid Nazarov",
    projectId: "proj-1",
    date: "2024-01-22",
    areaCompleted: 26,
    description: "Exterior wall completion on residential complex",
    ratePerSquareMeter: 15,
    earnings: 390,
  },
  {
    id: "log-9",
    workerId: "worker-1",
    workerName: "Farid Nazarov",
    projectId: "proj-9",
    date: "2023-12-15",
    areaCompleted: 20,
    description: "Concrete foundation work for water treatment facility",
    ratePerSquareMeter: 15,
    earnings: 300,
  },
];

// Navigation items are now handled in BottomNavigation component with proper icons

// Material units
export const materialUnits = ["kg", "m²", "L", "pcs", "m³", "m"];

// Project statuses
export const projectStatuses = [
  { value: "planning", label: "Planning", color: "bg-yellow-500" },
  { value: "active", label: "Active", color: "bg-green-500" },
  { value: "paused", label: "Paused", color: "bg-orange-500" },
  { value: "completed", label: "Completed", color: "bg-blue-500" },
];

// Mock material requests
export const mockMaterialRequests: MaterialRequest[] = [
  {
    id: "req-1",
    workerId: "worker-1",
    workerName: "Farid Nazarov",
    projectId: "proj-1",
    projectName: "Residential Complex A",
    materialName: "Cement",
    requestedQuantity: 500,
    unit: "kg",
    urgency: "high",
    reason: "Running low on cement, need for foundation work",
    status: "pending",
    requestDate: "2024-01-22",
    notes: "Need by Friday to stay on schedule",
  },
  {
    id: "req-2",
    workerId: "worker-2",
    workerName: "Jamshid Karimov",
    projectId: "proj-2",
    projectName: "Office Building B",
    materialName: "Steel Rebar",
    requestedQuantity: 200,
    unit: "kg",
    urgency: "medium",
    reason: "Additional rebar needed for column reinforcement",
    status: "approved",
    requestDate: "2024-01-20",
    approvedBy: "Ahmad Rahimi",
    approvedDate: "2024-01-21",
  },
  {
    id: "req-3",
    workerId: "worker-4",
    workerName: "Rustam Asadov",
    projectId: "proj-2",
    projectName: "Office Building B",
    materialName: "Paint",
    requestedQuantity: 50,
    unit: "L",
    urgency: "low",
    reason: "Need more paint for interior walls",
    status: "fulfilled",
    requestDate: "2024-01-18",
    approvedBy: "Ahmad Rahimi",
    approvedDate: "2024-01-19",
  },
];

// Worker specializations
export const workerSpecializations = [
  "Mason",
  "Carpenter",
  "Electrician",
  "Plumber",
  "Painter",
  "Roofer",
  "Welder",
  "General Labor",
];

// Material request urgency levels
export const urgencyLevels = [
  { value: "low", label: "Low Priority", color: "bg-green-500" },
  { value: "medium", label: "Medium Priority", color: "bg-yellow-500" },
  { value: "high", label: "High Priority", color: "bg-red-500" },
];

// Material request statuses
export const requestStatuses = [
  { value: "pending", label: "Pending", color: "bg-yellow-500" },
  { value: "approved", label: "Approved", color: "bg-blue-500" },
  { value: "rejected", label: "Rejected", color: "bg-red-500" },
  { value: "fulfilled", label: "Fulfilled", color: "bg-green-500" },
];
